name: Demo

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      # after pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: 🌌 Build Valaxy Cli
        run: pnpm build

      - name: 📖 pull yunyoujun.cn posts
        run: |
          git clone -b valaxy https://github.com/YunYouJun/yunyoujun.github.io
          cp -rf yunyoujun.github.io/source/_posts/posts/* demo/yun/pages/posts

      - name: ☁️ Build Yun Demo (SSG)
        run: pnpm run build:demo

      # - name: Type Check
      #   run: pnpm run typecheck

      # - name: Unit Test
      #   run: pnpm run test:unit
