name: Demo

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      # after pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: 🌌 Build Valaxy Cli
        run: pnpm build

      # - name: 📖 pull yunyoujun.cn posts
      #   run: |
      #     git clone -b valaxy https://github.com/YunYouJun/yunyoujun.github.io
      #     cp -rf yunyoujun.github.io/pages/posts/* demo/yun/pages/posts

      - name: ☁️ Build Yun Demo (SSG)
        run: pnpm run build:demo
