name: PR Approved

on:
  pull_request_review:
    types:
      - submitted

jobs:
  reply:
    runs-on: ubuntu-latest
    steps:
      - name: reply approved image
        if: github.event.review.state == 'approved'
        uses: actions-cool/maintain-one-comment@v3
        with:
          number: ${{ steps.pr.outputs.id }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ![Yun Good](https://raw.githubusercontent.com/YunYouJun/yun/main/images/meme/yun-good-alpha-compressed.png)
            <!-- YUN_PR_APPROVED -->
          body-include: '<!-- YUN_PR_APPROVED -->'
