name: PR Approved

on:
  pull_request_review:
    branches:
      - main
    types:
      - submitted

jobs:
  reply:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: reply yun approved image
        if: github.event.review.state == 'approved'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '<img width="200" src="https://user-images.githubusercontent.com/25154432/222963476-672010d2-6b54-478b-99c7-2c330f636bd0.png" alt="Yun Good!" />'
            })
